# required files
db_file     "~/.config/mpd/database"
log_file    "~/.config/mpd/log"

# optional
music_directory         "~/recitations"
playlist_directory      "~/recitations/playlists"
pid_file                "~/.config/mpd/pid"
state_file              "~/.config/mpd/state"
sticker_file            "~/.config/mpd/sticker.sl"

max_output_buffer_size "16384"
auto_update        "yes"  # automatically updates db
restore_paused     "yes"
bind_to_address    "/tmp/mpd_socket"

audio_output {
    type        "pulse"
    name        "pulse"
}

# audio visualizer setup
audio_output {
    type        "fifo"
    name        "Visualizer feed"
    path        "/tmp/mpd.fifo"
    format      "44100:16:2"
}
