###################################################################
# Setters
###################################################################

# General
set -g set-clipboard on
set -g mouse on
set -g detach-on-destroy off
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# colors
set -g status-justify left
set -g status-position bottom
set -g status-bg "#222222"
set -g status-right "#[fg=#7493ad,bold]%Y-%m-%d %H:%M"
set -g window-status-style fg=#7493ad,bold
set -g window-status-current-style fg=#7493ad,bold
set -g status-left "#[fg=#7493ad,bold][#S] "
set -g default-terminal "tmux-256color"
set -as terminal-features ",tmux-256color:RGB"
set -g allow-passthrough on


###################################################################
# key bindings
###################################################################

# prefix key
unbind C-b
set -g prefix C-Space

# split bindings
bind "'" split-window -v -c "#{pane_current_path}"
bind \\ split-window -h -c "#{pane_current_path}"
unbind %
unbind '"'

# Remove confirmation of closing
unbind x
bind x kill-pane

# New bindings
bind c new-window -c "#{pane_current_path}"
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5
# ts keybinding
unbind f
bind-key -r f run-shell "tmux neww ~/dotfiles/scripts/ts"
# gitub opener
unbind g
bind-key -r g run "~/dotfiles/scripts/open-github.sh"
# opening vault
bind-key -r q run-shell "~/dotfiles/scripts/ts ~/vault"

# copy mode with vim
bind -r m resize-pane -Z
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "xclip -sel clip -i"
bind P paste-buffer
unbind -T copy-mode-vi MouseDragEnd1Pane

###################################################################
# List of tmux plugins
###################################################################

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'kkga/tmux-bidi'

# binidng of vim
is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(n?vim|vimdiff)$'"
bind -n C-h if-shell "$is_vim" "send-keys C-h" "select-pane -L"
bind -n C-j if-shell "$is_vim" "send-keys C-j" "select-pane -D"
bind -n C-k if-shell "$is_vim" "send-keys C-k" "select-pane -U"
bind -n C-l if-shell "$is_vim" "send-keys C-l" "select-pane -R"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

