ytdl-format="--extractor-args youtube:player_client=default,-android_sdkles bestvideo[height<=480]+bestaudio/best[height<=480]/best"
profile=fast
hwdec-codecs=h264,hevc,mpeg2

# specific to my low specs laptop
vo=gpu
hwdec=vaapi
gpu-api=opengl
idle=yes
force-window=yes
input-ipc-server=/tmp/mpvsocket
gpu-context=x11
# sync video and audio drift
# video-sync=display-resample
# vd-lavc-dr=yes


# Screenshots
screenshot-template="~/Pictures/SnapShots/mpv-%F-T%wH.%wM.%wS.%wT-F%{estimated-frame-number}"
screenshot-format=png					# Set screenshot format
screenshot-png-compression=0			# Range is 0 to 10. 0 being no compression.
screenshot-tag-colorspace=yes
screenshot-high-bit-depth=yes			# Same output bitdepth as the video

#OSC/OSD
osc=no
# uosc script provides seeking & volume indicators (via flash-timeline and flash-volume commands)
osd-bar=no
border=no

# Font
osd-font="JetBrainsMono Nerd Font"
osd-font-size=37
sub-font-size=70

#Audio
volume-max=200
volume=60
alang=en,eng,english,ar,ara,arabic

save-position-on-quit=yes
cache=auto
cache-secs=60
# keep-open-pause=yes

[keep-open-video]
profile-cond=video
keep-open=yes

[network]
profile-cond=get("stream-open-filename", ""):match("^https?://")
resume-playback=no
