ytdl-format="--extractor-args youtube:player_client=default,-android_sdkles bestvideo[height<=480]+bestaudio/best[height<=480]/best"

# specific to my low specs laptop
# vo=gpu
# gpu-api=opengl
profile=fast
video-sync=audio
vd-lavc-dr=yes
hwdec=vaapi-copy
hwdec-codecs=h264,hevc,mpeg2
no-keepaspect-window


# Screenshots
screenshot-template="~/Pictures/SnapShots/mpv-%F-T%wH.%wM.%wS.%wT-F%{estimated-frame-number}"
screenshot-format=png
screenshot-png-compression=0
screenshot-tag-colorspace=yes
screenshot-high-bit-depth=yes

#OSC/OSD
osc=no
# uosc script provides seeking & volume indicators (via flash-timeline and flash-volume commands)
osd-bar=no
border=no

# Font
osd-font="JetBrainsMono Nerd Font"
osd-font-size=37
sub-font-size=70

#Audio
volume-max=200
volume=60
alang=en,eng,english,ar,ara,arabic

save-position-on-quit=yes
cache=auto
cache-secs=60
# keep-open-pause=yes

[keep-open-video]
profile-cond=video
keep-open=yes

[network]
profile-cond=get("stream-open-filename", ""):match("^https?://")
resume-playback=no
