-- vim.pack.add({
--     { src = "https://github.com/ThePrimeagen/harpoon", version = "harpoon2" }
-- })
--
-- local harpoon = require("harpoon")
--
-- harpoon.setup({
--     menu = {
--         width = vim.api.nvim_win_get_width(0) - 4,
--     },
--     settings = {
--         save_on_toggle = true,
--     },
-- })
--
-- vim.keymap.set("n", "<leader>a", function() harpoon:list():add() end)
-- vim.keymap.set("n", "<C-e>", function() harpoon.ui:toggle_quick_menu(harpoon:list()) end)
--
-- vim.keymap.set("n", "<M-h>", function() harpoon:list():select(1) end)
-- vim.keymap.set("n", "<M-t>", function() harpoon:list():select(2) end)
-- vim.keymap.set("n", "<M-n>", function() harpoon:list():select(3) end)
-- vim.keymap.set("n", "<M-s>", function() harpoon:list():select(4) end)
